#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Disable concurent to run `check-types` after ESLint in lint-staged
# npx lint-staged --concurrent false

# use commitizen when run 'git commit'
exec < /dev/tty && npx cz --hook || true